site_name: 寒晶雪的文档站
site_url: https://hanjingxue-boling.github.io/Whiteboard/
site_description: Hanjingxue 的个人在线文档站。
site_author: Hanjingxue Boling

repo_name: Whiteboard
repo_url: https://github.com/Hanjingxue-Boling/Whiteboard  #仓库链接
edit_uri: ""

theme:


theme:
    name: material
    language: zh    
    highlightjs: true
    palette:
      - media: "(prefers-color-scheme: light)" 
        scheme: default
        primary: green
        accent: light blue
        toggle:
          icon: material/weather-night
          name: 切换到深色模式
      - media: "(prefers-color-scheme: dark)" 
        scheme: slate
        primary: blue
        accent: light green
        toggle:
          icon: material/weather-sunny
          name: 切换到浅色模式
    features:
      - navigation.tabs
      - content.tabs.link #启用内容页
    logo: assets/fox.png

nav:
    - 主页: index.md
    - 译文归档:
      - translation/about.md
      - 新闻归档:
        - translation/archives/about.md
        - 2021-07:
          - translation/archives/xfce-gsoc-2021.md
          - translation/archives/opensuse-cc.md
          - translation/archives/fedora-dpg.md
          - translation/archives/github-2021-07-27.md
        - 2021-08:
          - translation/archives/xfce-2021-08-02.md
          - translation/archives/google-2021-08-04.md
          - translation/archives/xfce-2021-08-17.md
          - translation/archives/xfce-2021-08-17-02.md
          - translation/archives/fedora-dpg-02.md
        - 2021-09:
          - translation/archives/xfce-2021-09-12.md
          - translation/archives/xfce-09-17.md
          - translation/archives/fedora-nest-2021.md
        - 2021-10:
          - translation/archives/kde-network-china-2021.md
        - 2021-11:
          - translation/archives/fedora35-released.md
          - translation/archives/xfce-2021-11-26.md
        - 2021-12:
          - translation/archives/xfce-2021-12-10.md
          - translation/archives/eff-chrome-manifestv3.md
        - 2022-01:
          - translation/archives/xfce-2022-01-21.md
      - OpenBSD 文档归档:
        - translation/OpenBSD-zh/about.md
        - FAQ:
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - Building the System from Source.md
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - Disk Setup.md
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - Installation Guide.md
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - Keyboard and Display Controls.md
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - Multimedia.md
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - Networking.md
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - Package Management.md
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - The X Window System.md
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - Virtual Private Networks (VPN) .md
          - translation/OpenBSD-zh/openbsd-faq/OpenBSD FAQ - Virtualization.md
        - Others:
          - translation/OpenBSD-zh/other/OpenBSD - Following -current and using snapshots.md
          - translation/OpenBSD-zh/other/OpenBSD - Mailing Lists .md
          - translation/OpenBSD-zh/other/OpenBSD - Problem Reports.md
          - translation/OpenBSD-zh/other/OpenBSD - Upgrade Guide 6.9 to 7.0.md
      - 2021-10:
        - translation/gimp-mirror-policy.md
      - 2022-02:
        - translation/donation-help-us.md
      - 2022-03:
        - translation/xfce4-terminal-0.9.2.md
        - translation/gimp-gsoc-2022.md
        - translation/blender-3.1.md
        - translation/xfce-gsoc-2022.md
        - translation/libreoffice-gsoc-2022.md
        - translation/plan-to-drop-soft.o.o.md
        - translation/openSUSE-code-of-conduct.md
      - 2022-04:
        - translation/yast-d-installer.md
        - translation/xfce4-terminal-1.0.0.md
        - translation/xfce-setting-gui.md
      - 2022-05:
        - translation/fedora36-released.md
        - translation/2022-05-17-theevilskeleton.md
        - translation/blender-events-in-2022.md
      - 2022-06:
        - translation/gimp-gsoc-2022-02.md
        - translation/open-letter-intel-fsp.md
    - 站内杂谈: 
      - essay/about.md
      - Linux 备忘录: 
        - essay/memo/opensuse.md
        - essay/memo/other-configs.md
        - essay/memo/eyecandy-kde.md
        - essay/memo/alias-tips.md
        - essay/memo/opencc.md
        - essay/memo/Tachidesk-quick-setup.md
      - 其他:
        - essay/others/2021-08.md
        - essay/others/anime-recommad.md
        - essay/others/adjust-win11-for-popurse.md
        - essay/others/fonts-and-measurement.md
        - essay/others/about-why.md
        - essay/others/use-rss-sub.md
        - 贡献者指南（已归档）:
          - essay/others/contribute/about.md
          - essay/others/contribute/base-01.md
          - essay/others/contribute/base-02.md
    - 随笔&日常:
      - essay/main/about.md
      - essay/main/2022-02-12.md
      - essay/main/2022-03-05.md
      - essay/main/2022-03-30.md
      - essay/main/2022-04-01.md
      - essay/main/2022-04-09.md
      - essay/main/2022-04-11.md
      - essay/main/2022-04-12.md
      - essay/main/2022-04-13.md
      - essay/main/2022-04-14.md
      - essay/main/2022-04-21.md
      - essay/main/2022-04-26.md
      - essay/main/2022-05-03.md
      - essay/main/2022-05-05.md
      - essay/main/2022-05-10.md
      - essay/main/2022-05-16.md
      - essay/main/2022-05-19.md
      - essay/main/2022-05-21.md
      - essay/main/2022-05-22.md
      - essay/main/2022-05-27.md
      - essay/main/2022-06-01.md
      - essay/main/2022-06-05.md
    - 站外归档:
      - archives/about.md
      - archives/goodies.md
      - archives/index.md
      - archives/glob-expression.md
      - archives/delete-hide-files.md
    - 关于: 
      - about/about-me.md
      - about/friends.md
      - about/license.md

markdown_extensions:
  #启用缩略语
  - abbr
  - pymdownx.snippets
  #启用警示标识
  - admonition
  - pymdownx.details
  - pymdownx.superfences 
  #启用注释
  - attr_list
  - md_in_html
  - pymdownx.superfences
  #启用按钮
  - attr_list
  #启用内容页
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  #启用脚注
  - footnotes
  #启用文本格式化
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  #启用图片
  - attr_list
  - md_in_html
  #启用列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  #启用图标 https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search

extra:
  homepage: https://hanjingxue-boling.github.io/Whiteboard/

copyright: Some copyright reserved. 2021-2022 Hanjingxue Boling.
