site_name: Boling's Whiteboard
site_url: https://hanjingxue-boling.github.io/Whiteboard/
site_description: Hanjingxue Boling's web blog.
site_author: Hanjingxue Boling

repo_url: https://github.com/Hanjingxue-Boling/Whiteboard  #仓库链接
edit_uri: ""

theme:
    name: mkdocs
    locale: zh_CN  #站点文字设置为中文
    highlightjs: true
    navigation_depth: 3  #侧边栏中导航树的最大深度

nav:
    - 主页: index.md
    - 博客: 
      - 目录: blog/index.md
      - blog/hellow-world.md
    - 翻译文稿: 
      - Index: translation/index.md
    - 随想: 
      - Index: essay/index.md
    - 关于: about.md

copyright: Copyright &copy; 2022 <a href="https://github.com/Hanjingxue-Boling">Hanjingxue Boling</a>.