site_name: 寒晶雪的白板
site_url: https://hanjingxue-boling.github.io/Whiteboard/
site_description: Hanjingxue Boling's web blog.
site_author: Hanjingxue Boling

repo_name: 博客源码仓库
repo_url: https://github.com/Hanjingxue-Boling/Whiteboard  #仓库链接
edit_uri: ""

theme:
    name: material
    language: zh    
    highlightjs: true
    palette: #切换日夜间模式
      - scheme: default
        primary: green
        accent: light blue
        toggle:
          icon: material/weather-sunny
          name: 切换到日间模式
      - scheme: slate
        primary: blue
        accent: light green
        toggle:
          icon: material/weather-night
          name: 切换至夜间模式
    features:
      - navigation.tabs
      - content.tabs.link #启用内容页
    logo: assets/fox.png

nav:
    - 主页: index.md
    - 博客: 
      - blog/index.md
      
      - blog/alias-tips.md
      - blog/eyecandy-kde.md
      - blog/adjust-win11-for-popurse.md
      - blog/use-rss-sub.md
      - blog/goodies.md
      - blog/hellow-world.md
    - 译文:
      - translation/index.md 
      - 2021-10:
        - translation/gimp-mirror-policy.md
      - 2022-02:
        - translation/donation-help-us.md
      - 2022-03:
        - translation/xfce4-terminal-0.9.2.md
        - translation/gimp-gsoc-2022.md
        - translation/blender-3.1.md
        - translation/xfce-gsoc-2022.md
        - translation/libreoffice-gsoc-2022.md
        - translation/plan-to-drop-soft.o.o.md
        - translation/openSUSE-code-of-conduct.md
      - 2022-04:
        - translation/yast-d-installer.md
        - translation/xfce4-terminal-1.0.0.md
    - 随想: 
      - essay/index.md
      - 备忘录: 
        - essay/memo-opensuse.md
      - 随笔:
        - essay/2022-02-12.md
        - essay/2022-03-05.md
        - essay/2022-03-30.md
        - essay/2022-04-01.md
        - essay/2022-04-09.md
        - essay/2022-04-11.md
    - 关于: 
      - about/about-me.md
      - about/friends.md
      - about/license.md

markdown_extensions:
  #启用缩略语
  - abbr
  - pymdownx.snippets
  #启用警示标识
  - admonition
  - pymdownx.details
  - pymdownx.superfences 
  #启用注释
  - attr_list
  - md_in_html
  - pymdownx.superfences
  #启用按钮
  - attr_list
  #启用内容页
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  #启用脚注
  - footnotes
  #启用文本格式化
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  #启用图片
  - attr_list
  - md_in_html
  #启用列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  #启用图标 https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date-localized: #启用时间戳
      type: iso_date
      enable_creation_date: true
      exclude:
        - index.md
        - translation/index.md
        - essay/index.md
        - blog/index.md

extra:
  homepage: https://hanjingxue-boling.github.io/Whiteboard/

copyright: Some copyright reserved. 2021-2022 Hanjingxue Boling.