site_name: Boling's Whiteboard
site_url: https://hanjingxue-boling.github.io/Whiteboard/
site_description: Hanjingxue Boling's web blog.
site_author: Hanjingxue Boling

repo_url: https://github.com/Hanjingxue-Boling/Whiteboard  #仓库链接
edit_uri: ""

theme:
    name: material
    language: zh    #material 的语言设置
    #locale: zh_CN  #站点文字设置为中文；适用于默认主题
    highlightjs: true
    #navigation_depth: 3  #侧边栏中导航树的最大深度；适用于默认主题
    palette:  #material 的主题色设置
      scheme: default
      primary: blue grey
      accent: light blue

nav:
    - 主页: index.md
    - 博客: 
      - blog/index.md
      - blog/hellow-world.md
    - 翻译文稿: 
      - translation/index.md
      - translation/gimp-mirror-policy.md
      - translation/donation-help-us.md
      - translation/xfce4-terminal-0.9.2.md
    - 随想: 
      - essay/index.md
      - essay/2022-02-12.md
      - essay/2022-03-05.md
    - 关于: about.md
